# Generated by Django 2.0 on 2018-09-26 18:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('fedora_uri', models.CharField(max_length=512)),
                ('identifier', models.CharField(max_length=256)),
                ('package_type', models.CharField(choices=[('aip', 'AIP'), ('dip', 'DIP')], max_length=10)),
                ('process_status', models.CharField(choices=[(10, 'Transfer saved'), (20, 'Accession record created'),
                 (30, 'Grouping component created'), (40, 'Transfer component created')], max_length=50)),
                ('transfer_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('accession_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
