# Generated by Django 2.0.8 on 2018-10-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='process_status',
            field=models.CharField(choices=[(10, 'Transfer saved'), (20, 'Accession record created'), (30, 'Grouping component created'),
                                   (40, 'Transfer component created'), (50, 'Digital object created')], max_length=50),
        ),
    ]
