# Generated by Django 2.0.8 on 2018-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0003_auto_20181114_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='process_status',
            field=models.CharField(choices=[(10, 'Transfer saved'), (20, 'Accession record created'), (30, 'Grouping component created'),
                                   (40, 'Transfer component created'), (50, 'Digital object created'), (60, 'Updated data sent to Aurora')], max_length=50),
        ),
    ]
