# Generated by Django 2.0.13 on 2019-09-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0004_auto_20181119_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='process_status',
            field=models.CharField(choices=[(10, 'Transfer saved'), (20, 'Accession record created'), (30, 'Grouping component created'), (40, 'Transfer component created'), (
                50, 'Digital object created'), (60, 'Updated transfer data sent to Aurora'), (70, 'Updated Accession data sent to Aurora')], max_length=50),
        ),
    ]
