# Generated by Django 4.2.1 on 2023-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0014_package_ursa_major_accession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='origin',
            field=models.CharField(choices=[('aurora', 'Aurora'), ('legacy_digital', 'Legacy Digital Processing'), ('digitization',
                                   'Digitization'), ('av_digitization', 'Audiovisual Digitization')], default='aurora', max_length=20),
        ),
    ]
