name: Deploy

on:
  push:
    branches:
      - development
      - base
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    env:
      APPLICATION_NAME: aquarius

    services:
      docker:
        image: docker:stable
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Export secrets to environment variables
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Clone deploy scripts
        run: git clone https://github.com/RockefellerArchiveCenter/deploy_scripts.git

      - name: Make deploy scripts executable
        run: chmod +x deploy_scripts/*.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build docker image
        if: ${{ github.ref_name == 'development' }}
        run: docker build -t ${{APPLICATION_NAME}} --target build .

      - name: Push Docker image to ECR
        if: ${{ github.ref_name == 'development' }}
        run: bash deploy_scripts/containers/push_image_to_ecr.sh ${{APPLICATION_NAME}}
      
      - name: Retag Docker image
        if: ${{ github.ref_name == 'base' }}
        run: bash deploy_scripts/containers/add_tag_to_image.sh ${{APPLICATION_NAME}} dev prod